spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notifyhub
    username: notifyhub_app
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

notifyhub:
  default-channel: push
  rate-limit: 200
